
development:
  aws_bucket: "marqoomedia"
  aws_access_key: "AKIAIFOMCFC3A2GJIPZA"
  aws_secret_access: "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"


production:
  aws_bucket: "marqoomedia"
  aws_access_key: "AKIAIFOMCFC3A2GJIPZA"
  aws_secret_access: "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"
