
development:
  aws_bucket: "marqoomedia"
  aws_access_key: "AKIAJSDSE7O524BFRDHQ"
  aws_secret_access: "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"


production:
  aws_bucket: "marqoomedia"
  aws_access_key: "AKIAJSDSE7O524BFRDHQ"
  aws_secret_access: "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"