
development:
  aws_bucket: "marqooapp"
  aws_access_key: "AKIAJICPI3ZBJ5FL5ZPQ"
  aws_secret_access: "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"


production:
  aws_bucket: "marqooapp"
  aws_access_key: "AKIAJICPI3ZBJ5FL5ZPQ"
  aws_secret_access: "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"
