
development:
  aws_bucket: "marqoomedia"
  aws_access_key: "AKIAJHLHVL6VQWGDH3ZQ"
  aws_secret_access: "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"


production:
  aws_bucket: "marqoomedia"
  aws_access_key: "AKIAJHLHVL6VQWGDH3ZQ"
  aws_secret_access: "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"
