
development:
  aws_bucket: "marqoomedia"
  aws_access_key: "AKIAJZTGHMJI7XLAVKTA"
  aws_secret_access: "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"


production:
  aws_bucket: "marqoomedia"
  aws_access_key: "AKIAJZTGHMJI7XLAVKTA"
  aws_secret_access: "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"